artifact_location: /app/scripts/I=postgresql:/mlflow:mlflow@mlflow_db:5432/mlflow/0
creation_time: 1726928746701
experiment_id: '0'
last_update_time: 1726928746701
lifecycle_stage: active
name: Default
