name: ci
on:
  push:
    branches:
      - publicdocs
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: "#juin24cmlops_crypto"
          payload: |
            {
              "Public-Page Update(PR)": ${{ github.event.pull_request.title }},
              "Author": "${{ github.event.pull_request.user.login }},
              "URL": 'https://dstmlopscrypto.github.io/MainCrypto/',
              "Job-Status": ${{ job.status }}
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
