name: Deploy to Dev

on:
  pull_request:
    branches: ["dev"]
    types: [opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test_group1:
    name: Testing containers
    # The type of runner
    runs-on: ubuntu-latest
    steps:
      # action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose python3
          sudo apt-get install python3-pip
          sudo apt-get install python3-psycopg2
          sudo apt-get install python3-pytest
          sudo apt-get install python3-fastapi
          sudo apt-get install -y python3-httpx
          sudo pip3 install python-multipart
          sudo pip3 install pydantic
          sudo pip3 install pytest-asyncio
          sudo pip3 install python-jose[cryptography]
          sudo pip3 install passlib[bcrypt]

      - name: Launch Container
        run: |
          docker-compose -f docker-compose-dev.yml up -d --build
        env:
          AIRFLOW_UID: 50000
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Run Pytest
        run: |
          python -m pytest tests/crypto/
          python -m pytest tests/api/
        env:
          CRYPTO_DB_HOST: localhost
          CRYPTO_DB_PORT: 5440
          CRYPTO_DB_NAME: cryptoDb
          CRYPTO_DB_USER: crypto
          CRYPTO_DB_PASSWORD: crypto
      - name: Tear down containers
        run: |
          docker-compose -f docker-compose-dev.yml down        
